# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Ahmed Elmahy
tagline:          'Personal website'
description:      'Final Year Medical Student, Researcher and Programmer'
#url: 	          / 
baseurl: 	  https://ahmedelmahy.github.io/         

author:
  name:           'Ahmed Elmahy'
  url:            https://twitter.com/elmahyAG
logo:             AhmedElmahy.jpg
avatar:           AhmedElmahy.jpg
paginate:         5


# Gems
gems:
  - jekyll-paginate
  - jekyll-gist


